import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawn } from "node:child_process";

function runGeometry(payload) {
  return new Promise((resolve, reject) => {
    const child = spawn("python3", ["scripts/braid_geometry.py"], {
      cwd: process.cwd(),
      stdio: ["pipe", "pipe", "pipe"]
    });
    const stdout = [];
    const stderr = [];
    child.stdout.on("data", (chunk) => stdout.push(chunk));
    child.stderr.on("data", (chunk) => stderr.push(chunk));
    child.on("error", reject);
    child.on("close", (code) => {
      const errorText = Buffer.concat(stderr).toString("utf8");
      if (code !== 0) return reject(new Error(errorText || `Geometry exited ${code}`));
      resolve(JSON.parse(Buffer.concat(stdout).toString("utf8")));
    });
    child.stdin.end(JSON.stringify(payload));
  });
}

function basePayload() {
  return {
    carrierCount: 16,
    diameterMm: 16,
    braidAngle: 34,
    strandWidthScale: 1,
    filamentCount: 25,
    denier: 1000,
    crossingMode: "diamond",
    visibleRows: 8,
    carriers: Array.from({ length: 16 }, (_, index) => ({
      no: index + 1,
      color: [0, 2].includes(index) ? "#e11912" : "#f6f5ee"
    }))
  };
}

test("crossing proof and rope are generated by one geometry contract", async () => {
  const payload = basePayload();
  const [rope, crossing] = await Promise.all([
    runGeometry({ ...payload, mode: "rope" }),
    runGeometry({ ...payload, mode: "crossing" })
  ]);

  assert.equal(rope.geometryModel, "unified_carrier_geometry");
  assert.equal(crossing.geometryModel, rope.geometryModel);
  assert.equal(crossing.crossSectionOrder, rope.crossSectionOrder);
  assert.equal(rope.beautySurfaceModel, "continuous_outward_lenticular_tow_shell");
  assert.equal(rope.closedPlasticSidewalls, false);
  assert.equal(rope.towEdgeModel, "rounded_down_outer_shell_edge");
  assert.equal(crossing.contactInterpolation, rope.contactInterpolation);
  assert.equal(crossing.contactMaximumHeightCompression, rope.contactMaximumHeightCompression);
  assert.equal(crossing.contactFaceModel, "C2_finite_flat_contact_patch");
  assert.equal(crossing.contactClearanceMm, rope.contactClearanceMm);
  assert.equal(crossing.yarnWidth, rope.yarnWidth);
  assert.equal(crossing.yarnThickness, rope.yarnThickness);
  assert.equal(
    crossing.derivedDimensions.eventSpacingAxialMm,
    rope.derivedDimensions.eventSpacingAxialMm
  );
  assert.equal(
    crossing.derivedDimensions.contactHalfLengthAxialMm,
    rope.derivedDimensions.contactHalfLengthAxialMm
  );
  assert.deepEqual(crossing.derivedDimensions, rope.derivedDimensions);
  assert.equal(crossing.mode, "crossing");
  assert.equal(crossing.surfacePieceCount, 2);
  assert.equal(crossing.crossingSource, "cropped_from_full_rope_topology");
  assert.equal(crossing.topologySource, rope.topologySource);
  assert.equal(crossing.crossSectionFrameModel, rope.crossSectionFrameModel);
  assert.equal(rope.crossingDeformationModel, "continuous_across_width_saddle_field");
  assert.equal(rope.crossingEdgeTimingModel, "exact_unwrapped_line_intersection");
  assert.equal(crossing.ringSegments, rope.ringSegments);
  assert.deepEqual(crossing.yarns[0].crossingEvents, rope.yarns[0].crossingEvents);
  assert.deepEqual(crossing.yarns[1].crossingEvents, rope.yarns[1].crossingEvents);
  assert.equal(rope.mode, "rope");
  assert.equal(rope.surfacePieceCount, 16);
});

test("every bobbin remains one continuous S or Z carrier", async () => {
  const rope = await runGeometry({ ...basePayload(), mode: "rope" });
  assert.equal(rope.carrierPathModel, "one_continuous_bundle_per_carrier");
  assert.equal(rope.piecesPerCarrier, 1);
  assert.equal(rope.directionCounts.S, 8);
  assert.equal(rope.directionCounts.Z, 8);
  assert.equal(new Set(rope.yarns.map((yarn) => yarn.carrierNo)).size, 16);
  assert.ok(rope.yarns.every((yarn) => yarn.continuousCarrier));
  assert.ok(rope.yarns.every((yarn) => yarn.pathPointCount > 64));
  assert.ok(rope.yarns.every((yarn) => yarn.crossingTransitions >= 2));
  assert.equal(rope.minimumCrossingEnvelopeClearance, 0);
  assert.equal(rope.contactWidthConstraint, "full_pitch_no_gap_width");
  assert.equal(rope.contactCompactionModel, "packing_density_increase");
  assert.ok(rope.minimumContactAreaRetention > 0.89);
  assert.ok(rope.surfaceBaseRadius < rope.radius);
  assert.equal(rope.filamentCount, 25);
  assert.equal(rope.denier, 1000);
  assert.ok(rope.yarns.every((yarn) =>
    yarn.mesh.vertices.every(Number.isFinite) && yarn.mesh.indices.length > 0
  ));
  assert.deepEqual(
    rope.yarns.filter((yarn) => yarn.color === "#e11912").map((yarn) => yarn.carrierNo),
    [1, 3]
  );
});

test("diameter and braid angle change dimensions without changing topology", async () => {
  for (const [diameterMm, braidAngle] of [[12, 28], [16, 34], [24, 45]]) {
    const rope = await runGeometry({
      ...basePayload(),
      mode: "rope",
      diameterMm,
      braidAngle
    });
    assert.equal(rope.surfacePieceCount, 16);
    assert.deepEqual(rope.directionCounts, { S: 8, Z: 8 });
    assert.ok(rope.yarnWidth > 0);
    assert.ok(rope.yarnThickness > 0);
    assert.ok(rope.minimumCrossingTransitions >= 2);
  }
});

test("server and browser expose only the unified geometry endpoint", async () => {
  const [server, browser] = await Promise.all([
    readFile("server.js", "utf8"),
    readFile("public/app.js", "utf8")
  ]);
  assert.match(server, /scripts.*braid_geometry\.py/);
  assert.match(server, /\/api\/braid-geometry/);
  assert.doesNotMatch(server, /texgen_braid_mesh|\/api\/texgen-braid/);
  assert.match(browser, /\/api\/braid-geometry/);
  assert.doesNotMatch(browser, /\/api\/texgen-braid|requestTexgenMesh/);
  assert.doesNotMatch(browser, /polyesterProofVariant|legacyMaterial|bundle-v\d+/);
});
