import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawn } from "node:child_process";

function runGeometry(payload) {
  return new Promise((resolve, reject) => {
    const child = spawn("python3", ["scripts/braid_geometry.py"], {
      cwd: process.cwd(),
      stdio: ["pipe", "pipe", "pipe"]
    });
    const stdout = [];
    const stderr = [];
    child.stdout.on("data", (chunk) => stdout.push(chunk));
    child.stderr.on("data", (chunk) => stderr.push(chunk));
    child.on("error", reject);
    child.on("close", (code) => {
      const errorText = Buffer.concat(stderr).toString("utf8");
      if (code !== 0) return reject(new Error(errorText || `Geometry exited ${code}`));
      const serialized = Buffer.concat(stdout);
      const result = JSON.parse(serialized.toString("utf8"));
      Object.defineProperty(result, "serializedBytes", { value: serialized.byteLength });
      resolve(result);
    });
    child.stdin.end(JSON.stringify(payload));
  });
}

function runDimensions(payload) {
  return new Promise((resolve, reject) => {
    const child = spawn("python3", [
      "-c",
      "import json,sys; from scripts.braid_geometry import carrier_dimensions; print(json.dumps(carrier_dimensions(json.load(sys.stdin))))"
    ], {
      cwd: process.cwd(),
      stdio: ["pipe", "pipe", "pipe"]
    });
    const stdout = [];
    const stderr = [];
    child.stdout.on("data", (chunk) => stdout.push(chunk));
    child.stderr.on("data", (chunk) => stderr.push(chunk));
    child.on("error", reject);
    child.on("close", (code) => {
      if (code !== 0) return reject(new Error(Buffer.concat(stderr).toString("utf8")));
      resolve(JSON.parse(Buffer.concat(stdout).toString("utf8")));
    });
    child.stdin.end(JSON.stringify(payload));
  });
}

function basePayload() {
  return {
    carrierCount: 16,
    diameterMm: 16,
    braidAngle: 34,
    strandWidthScale: 1,
    filamentCount: 25,
    denier: 1000,
    denierScale: 0.7,
    crossingMode: "diamond",
    visibleRows: 8,
    carriers: Array.from({ length: 16 }, (_, index) => ({
      no: index + 1,
      color: [0, 2].includes(index) ? "#e11912" : "#f6f5ee"
    }))
  };
}

function median(values) {
  const ordered = [...values].sort((left, right) => left - right);
  return ordered[Math.floor(ordered.length / 2)];
}

function measuredMeshAngle(yarn, ringSegments, radius) {
  const values = [];
  let previous = null;
  for (let ring = 0; ring < yarn.pathPointCount; ring += 1) {
    const offset = (ring * ringSegments + Math.floor(ringSegments / 2)) * 3;
    const current = {
      x: yarn.mesh.vertices[offset],
      theta: Math.atan2(yarn.mesh.vertices[offset + 2], yarn.mesh.vertices[offset + 1])
    };
    if (previous) {
      let deltaTheta = current.theta - previous.theta;
      while (deltaTheta > Math.PI) deltaTheta -= Math.PI * 2;
      while (deltaTheta < -Math.PI) deltaTheta += Math.PI * 2;
      values.push(
        Math.atan(Math.abs(radius * deltaTheta / (current.x - previous.x))) * 180 / Math.PI
      );
    }
    previous = current;
  }
  return median(values);
}

function interiorRunLengths(values) {
  const runs = [];
  for (const value of values) {
    const last = runs.at(-1);
    if (last?.value === value) last.length += 1;
    else runs.push({ value, length: 1 });
  }
  return runs.slice(1, -1).map((run) => run.length);
}

test("crossing proof and rope are generated by one geometry contract", async () => {
  const payload = basePayload();
  const [rope, crossing] = await Promise.all([
    runGeometry({ ...payload, mode: "rope" }),
    runGeometry({ ...payload, mode: "crossing" })
  ]);

  assert.equal(rope.geometryModel, "unified_carrier_geometry");
  assert.equal(crossing.geometryModel, rope.geometryModel);
  assert.equal(crossing.crossSectionOrder, rope.crossSectionOrder);
  assert.equal(rope.beautySurfaceModel, "continuous_outward_lenticular_tow_shell");
  assert.equal(rope.closedPlasticSidewalls, false);
  assert.equal(rope.towEdgeModel, "rounded_down_outer_shell_edge");
  assert.equal(rope.towEdgeRollRatio, 0);
  assert.equal(crossing.contactInterpolation, rope.contactInterpolation);
  assert.equal(crossing.contactMaximumHeightCompression, rope.contactMaximumHeightCompression);
  assert.equal(crossing.contactFaceModel, "C2_finite_flat_contact_patch");
  assert.equal(crossing.contactClearanceMm, rope.contactClearanceMm);
  assert.equal(crossing.yarnWidth, rope.yarnWidth);
  assert.equal(crossing.yarnThickness, rope.yarnThickness);
  assert.equal(
    crossing.derivedDimensions.eventSpacingAxialMm,
    rope.derivedDimensions.eventSpacingAxialMm
  );
  assert.equal(
    crossing.derivedDimensions.contactHalfLengthAxialMm,
    rope.derivedDimensions.contactHalfLengthAxialMm
  );
  assert.deepEqual(crossing.derivedDimensions, rope.derivedDimensions);
  assert.equal(crossing.mode, "crossing");
  assert.equal(crossing.surfacePieceCount, 2);
  assert.equal(crossing.crossingSource, "cropped_from_full_rope_topology");
  assert.equal(crossing.topologySource, rope.topologySource);
  assert.equal(crossing.crossSectionFrameModel, rope.crossSectionFrameModel);
  assert.equal(rope.crossingDeformationModel, "continuous_across_width_saddle_field");
  assert.equal(rope.crossingEdgeTimingModel, "exact_unwrapped_line_intersection");
  assert.equal(crossing.ringSegments, rope.ringSegments);
  assert.ok(crossing.yarns[0].mesh.pathLengthMm > 0);
  assert.ok(rope.yarns[0].mesh.pathLengthMm > crossing.yarns[0].mesh.pathLengthMm);
  assert.deepEqual(crossing.yarns[0].crossingEvents, rope.yarns[0].crossingEvents);
  assert.deepEqual(crossing.yarns[1].crossingEvents, rope.yarns[1].crossingEvents);
  assert.equal(rope.mode, "rope");
  assert.equal(rope.surfacePieceCount, 16);
});

test("every bobbin remains one continuous S or Z carrier", async () => {
  const rope = await runGeometry({ ...basePayload(), mode: "rope" });
  assert.equal(rope.carrierPathModel, "one_continuous_bundle_per_carrier");
  assert.equal(rope.piecesPerCarrier, 1);
  assert.equal(rope.directionCounts.S, 8);
  assert.equal(rope.directionCounts.Z, 8);
  assert.equal(new Set(rope.yarns.map((yarn) => yarn.carrierNo)).size, 16);
  assert.ok(rope.yarns.every((yarn) => yarn.continuousCarrier));
  assert.ok(rope.yarns.every((yarn) => yarn.pathPointCount > 64));
  assert.ok(rope.yarns.every((yarn) => yarn.crossingTransitions >= 2));
  assert.equal(rope.minimumCrossingEnvelopeClearance, 0);
  assert.equal(rope.contactWidthConstraint, "full_pitch_no_gap_width");
  assert.equal(rope.contactCompactionModel, "packing_density_increase");
  assert.ok(rope.minimumContactAreaRetention > 0.89);
  assert.ok(rope.surfaceBaseRadius < rope.radius);
  assert.equal(rope.filamentCount, 25);
  assert.equal(rope.denier, 1000);
  assert.equal(rope.denierScale, 0.7);
  assert.equal(rope.effectiveDenier, 700);
  assert.equal(rope.denierPerEnd, 1000);
  assert.equal(rope.endsPerCarrier, 25);
  assert.equal(rope.totalCarrierDenier, 25000);
  assert.equal(rope.fitStatus, "ok");
  assert.ok(rope.contactPackingFraction < rope.derivedDimensions.maximumContactPackingFraction);
  assert.ok(rope.yarns.every((yarn) =>
    yarn.mesh.vertices.every(Number.isFinite) && yarn.mesh.indices.length > 0
  ));
  assert.deepEqual(
    rope.yarns.filter((yarn) => yarn.color === "#e11912").map((yarn) => yarn.carrierNo),
    [1, 3]
  );
});

test("polyester denier calibration reduces package area without changing topology", async () => {
  const [full, calibrated] = await Promise.all([
    runGeometry({ ...basePayload(), mode: "rope", denierScale: 1 }),
    runGeometry({ ...basePayload(), mode: "rope", denierScale: 0.7 })
  ]);

  assert.equal(calibrated.surfacePieceCount, full.surfacePieceCount);
  assert.ok(Math.abs(calibrated.derivedDimensions.polymerAreaMm2 / full.derivedDimensions.polymerAreaMm2 - 0.7) < 1e-9);
  assert.ok(calibrated.yarnThickness < full.yarnThickness);
});

test("denier and ends change tow mass and section without changing machine topology", async () => {
  const lowDenier = await runDimensions({ ...basePayload(), denier: 500 });
  const highDenier = await runDimensions({ ...basePayload(), denier: 1500 });
  const lowEnds = await runDimensions({ ...basePayload(), filamentCount: 12 });
  const highEnds = await runDimensions({ ...basePayload(), filamentCount: 35 });

  assert.ok(Math.abs(highDenier.polymerAreaMm2 / lowDenier.polymerAreaMm2 - 3) < 1e-9);
  assert.ok(Math.abs(
    highDenier.polymerAreaMm2
    - highDenier.effectiveCarrierDenier * 1000 / (9000 * 1380)
  ) < 1e-12);
  assert.ok(highDenier.thicknessMm > lowDenier.thicknessMm);
  assert.equal(highDenier.widthMm, lowDenier.widthMm);
  assert.ok(highDenier.equivalentEndDiameterMm > lowDenier.equivalentEndDiameterMm);

  assert.ok(Math.abs(highEnds.totalCarrierDenier / lowEnds.totalCarrierDenier - 35 / 12) < 1e-9);
  assert.ok(highEnds.thicknessMm > lowEnds.thicknessMm);
  assert.equal(highEnds.widthMm, lowEnds.widthMm);
});

test("packing limits reject loose and overfilled production recipes", async () => {
  const loose = await runDimensions({
    ...basePayload(),
    diameterMm: 10,
    denier: 300,
    filamentCount: 8
  });
  const overfilled = await runDimensions({
    ...basePayload(),
    diameterMm: 10,
    denier: 3000,
    filamentCount: 40
  });

  assert.equal(loose.fitStatus, "loose");
  assert.ok(loose.packingFraction < 0.35);
  assert.equal(overfilled.fitStatus, "overfilled");
  assert.ok(overfilled.contactPackingFraction > overfilled.maximumContactPackingFraction);
});

test("material library preserves accepted Polip and calibrated Polyester profiles", async () => {
  const [polip, polyester] = await Promise.all([
    readFile("data/materials/polip_rope.json", "utf8").then(JSON.parse),
    readFile("data/materials/polyester_satin.json", "utf8").then(JSON.parse)
  ]);
  assert.equal(polip.materialProfileId, "polip_rope");
  assert.equal(polip.status, "user_accepted");
  assert.equal(polip.denierScale, 1);
  assert.equal(polyester.materialProfileId, "polyester_satin");
  assert.equal(polyester.denierScale, 1);
  assert.equal(polyester.texture.worldSpaceU, true);
  assert.ok(polyester.texture.repeatPerMm > 0);
  assert.ok(polyester.texture.referenceMicroFibersPerEnd > 1);
  assert.ok(polyester.texture.aggregateSpecular > 0);
  assert.ok(polyester.texture.lightCarrier.colorBase > polyester.texture.colorBase);
  assert.ok(polyester.texture.lightCarrier.microRelief < polyester.texture.microRelief);
  assert.ok(polyester.texture.lightCarrier.microGrooveColor > polyester.texture.macroGrooveColor);
  assert.ok(polyester.texture.lightCarrier.colorSatinAmplitude > 0);
  assert.ok(polyester.texture.lightCarrier.colorSatinAmplitude < polyester.texture.colorSatinAmplitude);
  assert.ok(polyester.optics.lightCarrier.roughness <= polyester.optics.roughness);
  assert.equal(polyester.optics.specularIntensity, 0);
  assert.equal(polyester.optics.lightCarrier.specularIntensity, 0);
  assert.equal(polyester.optics.sheen, 0);
  assert.equal(polyester.optics.lightCarrier.sheen, 0);
  assert.ok(polyester.optics.lightCarrier.sheenRoughness > polyester.optics.sheenRoughness);
  assert.ok(polyester.optics.anisotropy > polip.optics.anisotropy);
  assert.ok(polyester.optics.bumpScale < polip.optics.bumpScale);
});

test("diameter and braid angle change dimensions without changing topology", async () => {
  for (const [diameterMm, braidAngle] of [[12, 28], [16, 34], [24, 45]]) {
    const rope = await runGeometry({
      ...basePayload(),
      mode: "rope",
      diameterMm,
      braidAngle
    });
    assert.equal(rope.surfacePieceCount, 16);
    assert.deepEqual(rope.directionCounts, { S: 8, Z: 8 });
    assert.ok(rope.yarnWidth > 0);
    assert.ok(rope.yarnThickness > 0);
    assert.ok(rope.minimumCrossingTransitions >= 2);
    assert.ok(Math.abs(rope.meshOuterDiameterMm - diameterMm) < 0.1);
    assert.ok(
      Math.abs(measuredMeshAngle(rope.yarns[0], rope.ringSegments, rope.radius) - braidAngle) < 0.25
    );
  }
});

test("machine schedules preserve exact 1/1, 2/2 and 3/3 over-under runs", async () => {
  for (const [crossingMode, span] of [["diamond", 1], ["regular", 2], ["hercules", 3]]) {
    const rope = await runGeometry({ ...basePayload(), mode: "rope", crossingMode });
    const sequence = rope.yarns[0].crossingEvents.map((event) => event.order);
    assert.ok(interiorRunLengths(sequence).every((length) => length === span));
    assert.equal(rope.derivedDimensions.patternRepeatRows, span * 2);
    assert.ok(Math.abs(
      rope.derivedDimensions.weaveRepeatAxialMm
      - rope.derivedDimensions.eventSpacingAxialMm * span * 2
    ) < 1e-9);
  }
});

test("odd carrier counts are rejected because S and Z families must balance", async () => {
  await assert.rejects(
    runDimensions({ ...basePayload(), carrierCount: 15 }),
    /carrierCount must be an even number/
  );
});

test("maximum machine size stays bounded and keeps balanced continuous carriers", async () => {
  const carrierCount = 48;
  const rope = await runGeometry({
    ...basePayload(),
    mode: "rope",
    carrierCount,
    visibleRows: 60,
    carriers: Array.from({ length: carrierCount }, (_, index) => ({
      no: index + 1,
      color: index % 7 === 0 ? "#e11912" : "#f6f5ee"
    }))
  });
  assert.equal(rope.visibleRows, 30);
  assert.equal(rope.surfacePieceCount, carrierCount);
  assert.deepEqual(rope.directionCounts, { S: 24, Z: 24 });
  assert.ok(rope.yarns.every((yarn) => yarn.continuousCarrier));
  assert.ok(Math.abs(rope.meshOuterDiameterMm - rope.diameterMm) < 0.1);
  assert.ok(rope.serializedBytes < 18 * 1024 * 1024);
});

test("server and browser expose only the unified geometry endpoint", async () => {
  const [server, browser, geometry, proof] = await Promise.all([
    readFile("server.js", "utf8"),
    readFile("public/app.js", "utf8"),
    readFile("scripts/braid_geometry.py", "utf8"),
    readFile("scripts/textile-proof-screenshot.mjs", "utf8")
  ]);
  assert.match(server, /scripts.*braid_geometry\.py/);
  assert.match(server, /\/api\/braid-geometry/);
  assert.doesNotMatch(server, /texgen_braid_mesh|\/api\/texgen-braid/);
  assert.doesNotMatch(server, /analyze-image|pattern\/solve|pattern\/predict|pattern\/simulate/);
  assert.doesNotMatch(server, /braidPredictor|braidSurfaceSimulator|patternSolver/);
  assert.match(server, /materialProfileId/);
  assert.match(server, /const materialProfiles = await loadMaterialProfiles\(\)/);
  assert.match(server, /payload\.denierScale = materialProfile\.denierScale/);
  assert.match(server, /materialProfile,/);
  assert.match(browser, /\/api\/braid-geometry/);
  assert.match(browser, /materialProfileId: ui\.materialProfile\.value/);
  assert.match(browser, /applyMaterialLighting\(mesh\.materialProfile\)/);
  assert.match(browser, /lighting\.softboxPosition/);
  assert.match(browser, /const optics = profile\.optics/);
  assert.match(browser, /const lightCarrier = optics\.lightCarrier/);
  assert.match(browser, /roughness: resolvedRoughness/);
  assert.match(browser, /sheenRoughnessMap: profileId === "polyester_satin"/);
  assert.match(browser, /specularIntensityMap: fiberMaps\.specular/);
  assert.match(browser, /specularIntensity: resolvedSpecularIntensity/);
  assert.match(browser, /lightCarrierOpticsMix/);
  assert.match(browser, /specularMapColorSpace/);
  assert.match(browser, /anisotropy: resolvedAnisotropy/);
  assert.match(browser, /rgb\(255,128,230\)/);
  assert.match(browser, /referenceMicroFibersPerEnd/);
  assert.match(browser, /aggregateFiberClusters/);
  assert.match(browser, /microGrooveColor/);
  assert.match(browser, /filamentColorVariation/);
  assert.match(browser, /microGrooveVisibility/);
  assert.match(browser, /periodicFiberNoise/);
  assert.match(browser, /pathLengthMm/);
  assert.match(browser, /textureProfile\.repeatPerMm/);
  assert.match(browser, /__BRAIDSTUDIO_RUNTIME_AUDIT__/);
  assert.match(browser, /state\.zoom = 24/);
  assert.doesNotMatch(browser, /geometryFromCarrierFiberShell|getCarrierFiberMaterial/);
  assert.doesNotMatch(browser, /emissiveMap|resolvedFiberScatter|specularColorMap|sheenColorMap/);
  assert.match(browser, /geometryMesh\.length \* 2\.15, 52, 80/);
  assert.match(browser, /drawMeasurementRulers/);
  assert.match(browser, /projectedPixelsPerMillimeter/);
  assert.match(browser, /recordDiameterProjectionAudit/);
  assert.match(browser, /maximumDiameterSpreadPx/);
  assert.doesNotMatch(browser, /ropeGroup\.rotation\.set\(0, -\.18, 0\)/);
  assert.match(proof, /maximumDiameterSpreadPx\) > 0\.25/);
  assert.match(proof, /Non-uniform projected diameter/);
  assert.doesNotMatch(browser, /\/api\/texgen-braid|requestTexgenMesh/);
  assert.doesNotMatch(browser, /polyesterProofVariant|legacyMaterial|bundle-v\d+/);
  assert.doesNotMatch(browser, /polyesterRenderLod|renderLod|visible\.push|angleRad2d|ribbonShader|accentColor/);
  assert.doesNotMatch(browser, /const lengthMm = 160|result\.(pitchMm|turns|circumference|laneWidth|repeatRows)/);
  assert.doesNotMatch(geometry, /flatWeave|cylindricalWeave|crossingWindow|ribbon_shader/);
  assert.match(geometry, /fit_status = "overfilled"/);
});

// Recover carrier identity from the rendered mesh at a fixed circumferential
// ray. This does not trust directionCounts or a claimed repeat in metadata.
function meshRayHits(yarn, ringSegments) {
  const points = [];
  let previousRaw = null, theta = 0;
  for (let ring = 0; ring < yarn.pathPointCount; ring++) {
    const i = (ring * ringSegments + Math.floor(ringSegments / 2)) * 3;
    const v = yarn.mesh.vertices;
    const raw = Math.atan2(v[i + 2], v[i + 1]);
    if (previousRaw === null) theta = raw;
    else theta += Math.atan2(Math.sin(raw - previousRaw), Math.cos(raw - previousRaw));
    points.push({ x: v[i], theta });
    previousRaw = raw;
  }
  const hits = [];
  for (let j = 1; j < points.length; j++) {
    const a = points[j - 1], b = points[j];
    const low = Math.min(a.theta, b.theta), high = Math.max(a.theta, b.theta);
    for (let k = Math.ceil(low / (2 * Math.PI)); k * 2 * Math.PI <= high; k++) {
      const t = (k * 2 * Math.PI - a.theta) / (b.theta - a.theta);
      if (t >= 0 && t < 1) hits.push({ x: a.x + t * (b.x - a.x), id: yarn.carrierNo });
    }
  }
  return { hits, windingSign: Math.sign(points.at(-1).theta - points[0].theta) };
}

test("16-carrier mesh returns to the same carrier after eight same-family blocks", async () => {
  for (const flip of [false, true]) {
    const mesh = await runGeometry({ ...basePayload(), visibleRows: 30, flip, denierScale: 1 });
    for (const [direction, sign] of [["S", 1], ["Z", -1]]) {
      const family = mesh.yarns.filter(y => y.direction === direction);
      assert.equal(family.length, 8);
      const hits = family.flatMap(yarn => {
        const result = meshRayHits(yarn, mesh.ringSegments);
        assert.equal(result.windingSign, sign);
        return result.hits;
      }).sort((a, b) => a.x - b.x);
      assert.ok(hits.length >= 9);
      for (let i = 0; i + 8 < hits.length; i++) {
        assert.equal(new Set(hits.slice(i, i + 8).map(h => h.id)).size, 8);
        assert.equal(hits[i].id, hits[i + 8].id);
        assert.ok(Math.abs(hits[i + 8].x - hits[i].x - mesh.derivedDimensions.helicalPitchAxialMm) < 1e-4);
      }
    }
  }
});
