server {
    listen 80;
    listen [::]:80;
    server_name braidstudio.minen.com.tr;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name braidstudio.minen.com.tr;

    ssl_certificate /etc/letsencrypt/live/braidstudio.minen.com.tr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/braidstudio.minen.com.tr/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    client_max_body_size 12m;

    location / {
        proxy_pass http://127.0.0.1:3017;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 90;
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
    }
}
